[package]
name = "enex2mf"
version = "0.1.0"
authors = ["Joe Mou <joe@mou.fo>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
html2md = { version = "0.2.6", path = "../html2md" }
pulldown-cmark = "0.2.0"
xml-rs = "0.8.0"
