[package]
name = "enex2mf"
version = "0.1.0"
authors = ["Joe Mou <joe@mou.fo>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
html2md = { path = "../html2md" }
pulldown-cmark = "0.2.0"
roxmltree = "0.4.1"
